config/routes.rb
Rails.application.routes.draw do
  resources :initiatives
  resources :committees
  resources :identities

  resources :carts do
    resources :cart_items, path: 'items'
  end
  resources :cart_items # in case there isn't a cart

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations:      'users/registrations' }

  devise_scope :user do
    get 'login' => 'devise/sessions#new'
    delete 'logout' => 'devise/sessions#destroy'
    get 'signup' => 'users/registrations#new'
    get 'signup_from_id' => 'users/registrations#new_from_id'
  end

  scope module: 'main' do
    get 'introduction'
    get 'principles'
    get 'strategy'
    get 'faq'
    get 'about/pac/bylaws', to: redirect(
      'https://docs.google.com/document/d/1BbKNamiQdlemLS28iGnkwrwar9vQ9HucK_S1PrZ2mu4/',
      status: 302)
    get 'about/pac/finances', to: redirect(
      'https://docs.google.com/spreadsheet/ccc?key=0AjmetJxi-p0VdGlJSkl5NDkxdlE4bVlLLWtYWEZtcWc',
      status: 302)
    get 'about/pac/fec_reports', to: redirect(
      'http://images.nictusa.com/cgi-bin/fecimg/?C00529743', status: 302)
    get 'about/c4/bylaws', to: redirect(
      'https://docs.google.com/document/d/1uQEetVLONuzNdY_EYvmPX5P5PHC0kgp6kE-cdeVOT0A',
      status: 302)
    get 'about/c4/finances', to: redirect(
      'https://docs.google.com/spreadsheet/ccc?key=0AjmetJxi-p0VdEg3ajFfTDJZM1VPaEZMRmd0LUJ0ZVE',
      status: 302)
    get 'about/c3/bylaws', to: redirect(
      'https://docs.google.com/document/d/1ZU8yNZVC1AnSEKHm9nLN6WlEB6K2Kn2e5J6Mb-e37AI',
      status: 302)
    get 'about/c3/finances', to: redirect(
      'https://docs.google.com/spreadsheet/ccc?key=0AjmetJxi-p0VdF8tSWwxcHJ1QTJzQWtRSzhMY1ZFSWc',
      status: 302)
    get 'fec'
    get 'help'
    get 'contact'
    get 'press'
    get 'security'
    get 'help/legal', action: 'help_legal'
    get 'tos'
    get 'privacy'
    namespace :press do
      get 'BNA-2015-03-19'
      get 'BNA-2014-05-09'
      get 'BNA-2013-11-15'
    end
    namespace :fec do
      get 'accessibility'
      get 'bitcoin'
      get 'bitcoin/caf', action: 'bitcoin_caf'
      get 'bitcoin/pacs', action: 'bitcoin_pacs'
      get 'bitcoin/aor', to: redirect(
        'https://docs.google.com/document/d/1AVuXrnNPynEcIq07MTgZPCjXMJICxtKeRH0jshYHVk8/',
        status: 302)
      get 'earmarks'
      get 'earmarks/aor', to: redirect(
        'https://docs.google.com/document/d/1YeVdRxEqC8fWnJGl9DgkcNVY6HmkCPEzyRxB_0wttU0/',
        status: 302)
      get 'laundering'
      get 'ravel_weintraub'
      get 'tplf'
      get 'volunteer_ip'
    end
  end

  namespace :facebook do
    resources :payments, only: :create
  end

  namespace :paypal do
    resources :transactions do
      member do
        patch 'refresh'
      end
    end
    resources :notifications, only: :create  # IPN
    resources :transaction_notifications, only: :create # PDT
  end

  namespace :stripe do
    resources :charges
  end
  mount StripeEvent::Engine => '/stripe/callback'

  namespace :admin do
    constraints IsAdmin do
      mount Resque::Server, at: 'resque'
    end
    root to: redirect('/')
    get '*any', to: redirect('/')
  end

  post 'versions/:id/revert' => 'versions#revert', :as => 'revert_version'

  root 'main#index'

  resources :profiles, except: [:show, :update, :edit, :destroy]
  resources :profiles, only: [:show, :update, :edit, :destroy], path: '/'

end

app/controllers/main/fec_controller.rb
class Main::FecController < ApplicationController
  def method_missing page
    if Dir.glob(File.join(Rails.root, 'app', 'views', 'main', 'fec', "#{page}.*")).blank?
      head status: 404
    else
      track! 'page load', page: page unless tor?
    end
  end
end

app/controllers/main/press_controller.rb
class Main::PressController < ApplicationController
  def method_missing page
    if Dir.glob(File.join(Rails.root, 'app', 'views', 'main', 'press', "#{page}.*")).blank?
      head status: 404
    else
      track! 'page load', page: page unless tor?
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def method_missing page
    if Dir.glob(File.join(Rails.root, 'app', 'views', 'main', "#{page}.*")).blank?
      head status: 404
    else
      track! 'page load', page: page unless tor?
    end
  end
end

app/helpers/main_helper.rb
module MainHelper
  def btc_anon_image name, size = 16
    image_tag "btc_anon/#{name}_#{size}.png", height: size, width: size
  end
end

app/views/main/contact.html.erb
<%= t "Contact us" %>

<% cache do %>
<div class="c b"><%= link_to "Press", press_path %> | <%= link_to "Security", security_path %></div>

<p>You can find us primarily on  <a href="https://plus.google.com/100183759660923071401/about">Google+</a> and <a href="http://twitter.com/makeyourlaws">Twitter</a>.</p>

<!-- , <a href="http://facebook.com/makeyourlaws">Facebook</a>,  -->

<p>If you would like to join the team, just <a href="https://groups.google.com/a/makeyourlaws.org/forum/#!forum/team">introduce yourself</a> on the team mailing list, <a href="https://www.pivotaltracker.com/n/projects/9217">find something that needs to be done</a>, and contribute.</p>

<br/>

<p>For <b>general contacts</b> including bug reports, questions about the project, requests for more information, offers of assistance, etc, please contact the <b>full team</b> at <a href="mailto:team@makeyourlaws.org">team@makeyourlaws.org</a>. Please note that all email sent to or from this address is <a href="https://groups.google.com/a/makeyourlaws.org/forum/#!forum/team">publicly archived</a> for transparency.</p>

<p>For <b>issues that require privacy</b>, such abuse reports, problems processing payments, private contact information, personally identifiable information about specific users, etc. please contact the Make Your Laws <b>core team</b> at <a href="mailto:core@makeyourlaws.org">core@makeyourlaws.org</a>. This email is privately archived and only accessible to the core team. <em><strong>Never</strong> email us any passwords, credit card information, or the like.</em></p>

<p>You can also email pac, c4, or c3 (as appropriate) @makeyourlaws.org, leave us voicemail at +1 (717) 4 MYL MYL <i><small>(469-5695)</small></i>, fax +1 (206) 350-1309, or send physical mail to 500 Westover Dr #8458, Sanford, NC 27330.</p>

<% end %>

app/views/main/faq.html.erb
<%= t "Frequently Asked Questions" %>

<% cache do %>
<ol>
	<li>
		<h3>Are you a PAC? Super PAC? Non profit?</h3>
		<p>All of the above, actually. We're a group of three separate but collaborating non-profit corporations:
			<ol>
				<li>Make Your Laws PAC, Inc. (MYL PAC), a 527 hybrid non-connected Super PAC (<a href="http://images.nictusa.com/cgi-bin/fecimg/?C00529743">FEC ID #C00529743</a>, EIN 46-0580579, <%= link_to "bylaws", about_pac_bylaws_path %>, <%= link_to "finances", about_pac_finances_path %>), handles candidate-related issues, like contributions to federal and state candidates or parties.</li>
				<li>Make Your Laws Advocacy, Inc. (MYL C4), a 501(c)4 (EIN 46-0587765, <%= link_to "bylaws", about_c4_bylaws_path %>, <%= link_to "finances", about_c4_finances_path %>), handles non-candidate-related advocacy issues, like contributions to voter initiative committees.</li>
				<li>Make Your Laws Inc. (MYL C3), a 501(c)3 (EIN 61-1686259, <%= link_to "bylaws", about_c3_bylaws_path %>, <%= link_to "finances", about_c3_finances_path %>), handles non-partisan, non-contribution-related issues, like voter education, forum creation, etc.
                    <ul>
                        <li><a href="/files/MYL C3 - IRS Form 1023.pdf">IRS Form 1023</a> and <a href="/files/MYL C3 - IRS Form 1023 addenda 2015-07-22.pdf">attachments</a></li>
                        <li><a href="/files/MYL C3 - 2015-09-14 IRS 501c3 confirmation.pdf">IRS 501(c)(3) confirmation letter</a></li>
                    </ul>
                </li>
			</ol>
		</p>
		<p>Of the three, only MYL PAC is currently active, and pays for all shared operating costs (e.g. this website). The other two are on hold until we <%= link_to "ask the FEC", fec_path %> for advice about how to handle some issues relating to PAC/C4/C3 triads.</p>
		<p>Although all MYL entities are tax-exempt nonprofit corporations, contributions to MYL PAC and MYL C4 are <strong>not</strong> tax deductible; contributions to MYL C3 are.</p>
	</li>

	<li>
		<h3>How do you get/spend your money?</h3>
		<p>Right now our costs are just this server, corporate filing fees, and the like, and are paid by the MYL founders. You can read <%= link_to "all our FEC reports", about_pac_fec_reports_path %>, or our financial spreadsheets above.</p>
		<p>We haven't yet launched our full website (where you'll be able to contribute easily to any political organization), but if you <%= link_to "create an account", signup_path %>, we'll let you know when that happens.</p>
	</li>

	<li>
		<h3>Who runs MYL?</h3>
		<ul>
			<li>Sai — Founder; President, Treasurer, &amp; Director</li>
			<li>Liz Fong-Jones — Vice-Treasurer &amp; Director</li>
			<li>Nick Staddon — Secretary &amp; Director</li>
		</ul>
	</li>
</ol>

<% end %>

app/views/main/fec.html.erb
<%= t "Our activity before the Federal Election Commission" %>

<% cache do %>
<ul>
    <li><strong>Pending:</strong> REG 2015-03 MYL PAC &amp; C4 <%= link_to "Should the FEC prohibit contribution laundering?", fec_laundering_path %></li>
    <li><strong>Deadlocked:</strong> REG 2015-04 MYL PAC &amp; C4, Public Citizen <%= link_to "Should the FEC amend its regulations in the wake of Citizens United?", fec_ravel_weintraub_path %></li>
    <li><strong>Deadlocked:</strong> AO 2015-03 Democracy Rules re. 501(c)(4) acting as conduit for political contributions — MYL comments in opposition <a href="/files/2015-06-10 MYL PAC and MYL C4 comment on AOR 2015-03 Democracy Rules.pdf">1</a> and <a href="/files/2015-08-08 MYL PAC and MYL C4 comment on AOR 2015-03 Democracy Rules drafts B & C.pdf">2</a></li>
    <li><strong>Pending:</strong> REG 2015-01 <a href="http://www.fec.gov/pages/fecrecord/2015/april/adminfinesreportingnoa.shtml">petition re fines and forms</a> — <a href="/files/2015-05-27 MYL PAC comment on fines and forms rulemaking REG 2015-01.pdf">MYL comments</a></li>
    <li><strong>Denied (2-4), in <a href="http://www.fec.gov/pages/fecrecord/2015/july/ltpfvfecnew.shtml">litigation</a>:</strong> REG 2014-06 <a href="http://www.fec.gov/pages/fecrecord/2014/december/debaterulemakingpetition.shtml">Level the Playing field</a> re. third party access to presidential debates — <a href="/files/2014-12-15 MYL PAC comment on candidate debates rulemaking.pdf">MYL comments</a>
    <li><strong>Submitted:</strong> <%= link_to "Should the FEC make its documents accessible?", fec_accessibility_path %></li>
	<li><strong>Draft:</strong> <%= link_to "Should you be allowed to make very flexible earmarks?", fec_earmarks_path %></li>
    <li><strong>Deadlocked (3-3):</strong> REG 2014-01 post-<em><a href="http://www.fec.gov/law/litigation/McCutcheon.shtml">McCutcheon</a></em> <a href="http://www.fec.gov/pages/hearings/McCutcheonRulemakingPublicHearing.shtml">rulemaking</a>: <a href="/files/2015-01-14 MYL PAC comment on McCutcheon rulemaking.pdf">official comments</a>, <a href="https://www.youtube.com/watch?v=rLwG_19wReU">testimony video</a> (<a href="/files/sai_mccutcheon_transcript.txt">transcript</a>)</li>
    <li><strong>Approved (4-2):</strong> AO 2014-20 MYL PAC <%= link_to "Are PACs allowed to receive contributions of intellectual property from foreign nationals' volunteer services? Yes.", fec_volunteer_ip_path %></li>
	<li><strong>Approved (6-0):</strong> AO 2014-02 MYL PAC <%= link_to "Are PACs allowed to accept limited Bitcoin contributions? Yes.", fec_bitcoin_path %></li>
    <li><strong>Deadlocked (3-3):</strong> AO 2013-15 CAF <%= link_to "Should PACs be allowed to accept Bitcoin contributions as 'money'? No.", fec_bitcoin_caf_path %></li>
	<li><strong>Deadlocked (2-3):</strong> AO 2013-17 TPLF <%= link_to "Should the Tea Party Leadership Fund be granted an exemption from campaign finance reporting?", fec_tplf_path %></li>
</ul>

<% end %>

app/views/main/fec_pending.html.erb
TODO: replace ouraornumberhere with 2013-whatever before linking this publicly.

<a name="top"></a>
<h1>Our FEC Advisory Opinion Request, <a href="#pdf">AO ouraornumberhere</a> (<a>Google doc</a>)</h1>

<p>Make Your Laws is developing innovative ways to apply the principles of liquid democracy. We're starting with US campaign finance, which is regulated in part by the <a href="http://fec.gov" target="_blank">Federal Elections Commission</a> (FEC).</p>

<p>We believe that our developments are entirely consistent with both the letter and the spirit of the law, but for the sake of transparency (and to prevent any legal liability) we want to be certain that the FEC agrees. The FEC has a fairly straightforward way to ask how their regulations apply to specific situations, called an a <a href="http://www.fec.gov/pages/brochures/ao.shtml" target="_blank">advisory opinion request</a> (AOR).</p>

<p>Make Your Laws PAC (MYL PAC) is the <%= link_to "arm of MYL", faq_path %> that deals with influencing US elections, and recently <a href='#pdf'>filed our first AOR</a>.</p>

<a name="earmarks"></a>
<div style="text-align: center;"><a href="#questions">Our questions</a> | <a href="#comment">How to participate</a></div>

<h2><a href="#earmarks">A little legal background: "earmarked" contributions</a></h2>

<p>An "earmark" is when you give money to a political action committee (PAC) like MYL PAC, asking that it be spent in a specific way. PACs are required to either obey the request or refuse to accept your money. The FEC has two main rules about earmarks — one <a href="http://www.gpo.gov/fdsys/pkg/CFR-2011-title11-vol1/xml/CFR-2011-title11-vol1-sec102-8.xml" target="_blank">for the general case</a>, some extra if it's <a href="http://www.gpo.gov/fdsys/pkg/CFR-2011-title11-vol1/xml/CFR-2011-title11-vol1-sec110-6.xml" target="_blank">for a specific candidate</a>.</p>

<p>There are strict <a href="http://www.fec.gov/pages/brochures/citizens.shtml#how_much" target="_blank">limits</a> on how much money can be given to a politician or party (aka "hard money"). If you make an earmarked contribution through an intermediary like MYL PAC, it counts as if made directly from you to the ultimate recipient.</p>

<p>However, if the PAC has any "direction or control" over how the money is spent, it doesn't count as an earmark at all. Instead, it's a contribution from you to the PAC (limit $5k/yr), and from the PAC to the recipient (limit ~<a href="http://www.fec.gov/pages/brochures/contrib.shtml#Contribution_Limits" target="_blank">$5-15k/yr</a> per recipient). This means that even if it only accepts money from ordinary people making relatively small donations, the PAC wouldn't be able to handle contributions from more than ~100-1000 people.</p>

<p>That's why we would prefer your contributions be considered earmarks and not direct contributions to MYL PAC. Also, we just don't <em>want</em> to control your decisions. We want to remain completely non-partisan, and making decisions about how your money is spent would compromise our neutrality.</p>

<a name="questions"></a>
<div style="text-align: center;"><a href="#top">Top</a> | <a href="#earmarks">What are earmarks?</a> | <a href="#comment">How to participate</a></div>

<h2><a href="#questions">What we're asking the FEC</a></h2>

<p>We encourage you to read our formal AOR document for the details — we've tried to ensure that it is clear and understandable to non-specialists — but here is a summary of what we are asking the FEC, and how it affects what you would be able to do on this site.</p>

<ol>
	<li><h3>May a contributor defer a decision to earmark a contribution, or alter an untriggered earmark?</h3>
		
		<p>This would let you set up an automatic monthly payment and choose how you want us to spend that money later on (like if you're using proxies as in 2(f) below).</p>
		<p>It would also let you change your mind about an earmarked contribution (e.g. to change the recipient or trigger) in case something happens <em>before</em> the triggering event happens.</p>
	</li>
	<li><h3>May a contributor make an earmark contingent on any clearly defined external conditions?</h3>
		
		<p>This would let you contributions more easily and flexibly, by setting conditions and letting us do the tracking and logistical work for you.</p>
		<p>We gave several types of earmarks we'd like you to be able to make:</p>
		
		<ol class="alpha italic">
			<li><p>"$100 to XYZ PAC; or if they do not or cannot accept the contribution, to MYL PAC; or if my contribution limit to MYL PAC is exceeded, to MYL C4"</p>
				
				<p>This would let us have a fallback so that in case something goes wrong, we can use your money to effectively do what you asked us in some other way.</p>
			</li>
			<li><p class="mb-n">"$500, divided equally among every Senator who votes in favor of Senate Bill A when/if it comes to floor vote; or if there is no vote or it has no votes in favor, to be contributed to Americans For A."</p></li>
			<li><p class="mb-n">"$50 to Senator Bob, if Senate Committee B approves Senate Bill C by date D; or to Citizens Against Senator Bob if the bill is not approved by Senate Committee B by that date."</p></li>
			<li><p>"$1,000, divided equally among every 2015 House candidate to whom Citizens For A Better E gives a score of 90% or better by the end of October 2014."</p>
				
				<p>These three would let you contribute money based on specific issues or legislation that you want to you support or oppose. We'd handle the work of tracking votes, outcomes, etc.</p>
				<p>It would also make collective action on a specific issue or bill much easier. By making contributions ahead of time, you could join together with people who agree with you on the issue in making your collective intent clear and raising funds while the debate is still fresh.</p>
			</li>
			<li><p>"$200 to F PAC, only in the event that pledges to F PAC total at least $10,000 or 500 contributors by Date G; or if the pledge requirement is not met, no contribution."</p>
				
				<p>This is the "Kickstarter model" for campaign finance. It lets you pledge contributions to small (or would-be) campaigns which need some minimum amount to be realisticaly viable.</p>
			</li>
			<li><p>"$50 per month, divided proportionally in whatever way MYL website user H recommends, to take effect unless I override this earmark within one week of being sent H's updated recommendations."</p>
				
				<p>This lets campaign finance work like a <%= link_to "liquid democracy", introduction_path %> in a way that's easy to use and completely transparent.</p>
				<p>As a contributor, you could set how much you want to spend per month, and have it spent based on the recommendations of people you trust ("proxies").</p>
				<p>Your proxies might include someone who is particularly knowledgable about some specific issue. You could also just proxy 100% to a friend who shares your values but is more politically active, who in turn picks experts for some issues and has their own opinions on others.</p>
				<p>As a politically active blogger, you could give your readers a link or widget that lets them easily include your recommendations in their monthly contribution plan (or just make a one-off contribution to support the issue you write about in a specific post).</p>
				<p>In all cases, the contributor retains complete control over how their money is spent (and we make sure all the laws are followed). The proxy system just gives an option that makes participation easier and social influence more transparent.</p>
			</li>
		</ol>
	</li>
	<li><h3>May MYL PAC notify potentially affected recipients of contingent earmarks?</h3>
		
		<p>This would let us automatically tell potential recipients (like your representatives) about earmarks that affect them — letting them know how people feel about an issue, demographic breakdowns (like their consituents' views), etc.</p>
		<p>We would make all of that information would public anyway; this question just asks whether we can <em>notify</em> potential recipients, so that they know in advance what's going on and so we can make everything more transparent.</p>
	</li>
	<li><h3>How would the answers to the above questions be different for contributions made by MYL PAC itself out of direct contributions to MYL PAC by its users, when its users give MYL PAC non-binding guidance on how they would prefer their money be used?</h3>
		
		<p>This would give us a fallback option in case something might not be allowed using an earmark but would be allowed if we have more control. It also helps make clearer for us how much we can communicate with you informally about how you want your money spent.</p>
	</li>
	<li><h3>Does MYL PAC's payment for the costs of payment processing and other direct costs of fundraising — including its payment of the general costs of website operation and advertisement overall — constitute an "independent expenditure" or "contribution"? How should such costs be reported?</h3>
		
		<p>PACs are required to report all their expenses, but some (like <a href="http://www.fec.gov/pages/brochures/indexp.shtml#IE" target="_blank">"independent expenditures"</a>), require more detailed reporting. It's mainly intended to make partisan PACs report money they spend mailing letters asking people to contribute to or vote for their preferred candidates, and to make Super PACs to report their advertising. These are benefits to transparency that we definitely support.</p>
		<p>However, we're non-partisan and want to make it easy for you contribute to <em>any</em> political recipient; we'd be treating thousands of different recipients (all across the political spectrum) in exactly the same way. It'd be fairly hard for us to separately report exactly what portion of our general website or advertising expenses are for any particular recipient.</p>
		<p>The regulation requiring extra reporting for such things just doesn't really apply to us, and we'd like to avoid the complications involved.</p>
	</li>	
</ol>


<a name="comment"></a>
<div style="text-align: center;"><a href="#top">Top</a> | <a href="#earmarks">What are earmarks?</a> | <a href="#questions">Our questions</a></div>
	
<h2><a href="#comment">How you can get involved</a></h2>

<p>We want to know what you think, and the FEC does too.</p>

<p>To tell us informally, just email <a href="mailto:team@makeyourlaws.org?subject=Comments%20AO%20ouraornumberhere">team@makeyourlaws.org</a> or use comments on the google doc.</p>

<p>To tell the FEC formally, just email <a href="mailto:ao@fec.gov?subject=Comments%20AO%20ouraornumberhere%20MYL%20PAC">ao@fec.gov</a> or fax the FEC's Secretary ((202) 208-3333) and Office of General Counsel ((202) 219-3923).</p>

<p>Make sure to mention the formal name of our request ("AO ouraornumberhere MYL PAC"), include your name and the name of any organization you represent. Be clear and polite, and give specific explanations for how you think our questions should be answered.</p>

<p>If you can, it's better to make a more formal-looking comment. General email comments usually get lumped together, whereas if you take a little extra time to make a good-looking PDF, it'll appear separately and be looked at more seriously.</p>

<p>There are no specific formatting requirements, but we suggest you use 12 pt Arial w/ 1.5 line spacing for body text; 1 inch margin; and have a header saying "(your [group's] name) comments on AO ouraornumberhere MYL PAC" &amp; the page # / # total pages.</p>

app/views/main/help.html.erb
<%= t "How to help" %>

<% cache do %>

<p>As you've probably noticed, the website is very bare-bones. We're just getting started! If you have ideas for how to edit the site, or would like to help code the real thing for which this is just a placeholder, please join us.</p>

<ul>
	<li><p><b>Spread the word.</b> Add us on <a href="https://plus.google.com/100183759660923071401/about">Google+</a>,  <a href="http://twitter.com/makeyourlaws">Twitter</a>, and <a href="http://facebook.com/makeyourlaws">Facebook</a> (though our Facebook is currently inactive). Tell your friends, forums, school, work — anyone you think would be interested in helping to shape their own government, wherever they live, worldwide.</p></li>
	<li><p><b>Learn more.</b> Read our <%= link_to "introduction", introduction_path %> to online liquid democracy, the <%= link_to "principles", principles_path %> of our organization, our bootstrapping <%= link_to "strategy", strategy_path %> for eventually replacing entire legislatures.</p></li>
	<li><p><b><a href="https://plus.google.com/100183759660923071401/posts/NQVuM65jZqp">Join the Make Your Laws team.</a></b> We're mostly volunteers, a group of people who want to make a platform to revolutionize the way that people participate in making their own laws.</p>
		<p>You can contribute as much or as little as you want. You don't need to ask permission or go through a job interview — just join up, contribute something, and interact with us to make sure that it fits with what we need.</p>
		<!-- <a href="https://www.pivotaltracker.com/s/projects/9217" title="Pivotal project tracker"><%= image_tag 'pivotal-tracker-32.png' %></a> -->
		<p>We need people with a wide variety of skills, including but not limited to: programming; website and user experience design; network operations; art design; research and analytics; legal research and representation; grant writing and monitoring; community and abuse management; liaisons with local governments, political organizations, and academics; cryptographic design and review; security auditing; customer support; political advocacy; public relations, and more.</p>
		<p>We want to work with existing projects if possible, not compete with them. If you know a project that would merge well with our needs, we'd like to talk.</p>
		<p>Lawyer, law student, paralegal, or just interested in legal issues? <%= link_to "See here", help_legal_path %>.</p>
		<p>If you think you can help, or know someone who can, please <%= link_to "contact", contact_path %> the team or just <a href="https://plus.google.com/100183759660923071401/posts/NQVuM65jZqp">introduce yourself</a> on our G+ page.</p></li>
	<li><p><b>Cash donations are not currently being accepted, pending the creation of our new payment system.</b></p>
		<p>Although all MYL entities are tax-exempt nonprofit corporations, contributions to MYL PAC and MYL C4 are <i>not</i> tax deductible; contributions to MYL C3 are.</p>
		<p>However, if you'd like you could contribute things on <a href="http://www.amazon.com/registry/giftlist/2SAX6IXCF1CYA">MYL C3's Amazon wish list</a>.  Because MYL C3 is a 501(c)3, such contributions are considered tax-deducible charitable donations in the US. <span class="light">(If you do get MYL C3 something, please <%= link_to "contact us", contact_path %> if you want an official thank-you / confirmation of contribution letter for tax documentation purposes.)</span>
	</li>
</ul>




<% end %>

app/views/main/index.html.erb
<%= t "Your one stop site for all political contributions" %>

<% cache do %>

<div class="flash notice">
    <ul class="flush">
        <li><%= link_to "Should the FEC prohibit contribution laundering?", fec_laundering_path %></li>
    </ul>
</div>

<h3>Make Your Laws is launching soon.</h3>

<p>When we do, you will be able to use this website to easily make all kinds of political contributions, using <%= link_to "flexible tools", fec_earmarks_path %> that empower normal people and transparently use the trust and advice relationships they already have.</p>

<p>This is our <%= link_to "first step", strategy_path %> towards our ultimate goal of making every legislature a <%= link_to "liquid democracy", introduction_path %> — one where you can participate as much you want, collaboratively author new legislation, have your values be accurately represented on every issue, and truly <em>make your laws</em>.</p>

<h3>Interested?</h3>

<p>If you <%= link_to "create an account", signup_path %>, we'll give you early access to the beta version.</p>


<h3>Want to contribute?</3>

<ul>
    <li>Make Your Laws PAC, Inc. (MYL PAC): <a href="https://bitpay.com/715630/donate">Bitcoin</a> ($100/yr max)</li>
    <li>Make Your Laws Advocacy, Inc. (MYL C4): <a href="https://bitpay.com/985380/donate">Bitcoin</a></li>
    <li>Make Your Laws, Inc. (MYL C3): <a href="https://bitpay.com/497391/donate">Bitcoin</li>
</ul>

<% end %>