config/routes.rb
Rails.application.routes.draw do
  resources :initiatives
  resources :committees
  resources :identities

  resources :carts do
    resources :cart_items, path: 'items'
  end
  resources :cart_items # in case there isn't a cart

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations:      'users/registrations' }

  devise_scope :user do
    get 'login' => 'devise/sessions#new'
    delete 'logout' => 'devise/sessions#destroy'
    get 'signup' => 'users/registrations#new'
    get 'signup_from_id' => 'users/registrations#new_from_id'
  end

  scope module: 'main' do
    get 'introduction'
    get 'principles'
    get 'strategy'
    get 'faq'
    get 'about/pac/bylaws', to: redirect(
      'https://docs.google.com/document/d/1BbKNamiQdlemLS28iGnkwrwar9vQ9HucK_S1PrZ2mu4/',
      status: 302)
    get 'about/pac/finances', to: redirect(
      'https://docs.google.com/spreadsheet/ccc?key=0AjmetJxi-p0VdGlJSkl5NDkxdlE4bVlLLWtYWEZtcWc',
      status: 302)
    get 'about/pac/fec_reports', to: redirect(
      'http://images.nictusa.com/cgi-bin/fecimg/?C00529743', status: 302)
    get 'about/c4/bylaws', to: redirect(
      'https://docs.google.com/document/d/1uQEetVLONuzNdY_EYvmPX5P5PHC0kgp6kE-cdeVOT0A',
      status: 302)
    get 'about/c4/finances', to: redirect(
      'https://docs.google.com/spreadsheet/ccc?key=0AjmetJxi-p0VdEg3ajFfTDJZM1VPaEZMRmd0LUJ0ZVE',
      status: 302)
    get 'about/c3/bylaws', to: redirect(
      'https://docs.google.com/document/d/1ZU8yNZVC1AnSEKHm9nLN6WlEB6K2Kn2e5J6Mb-e37AI',
      status: 302)
    get 'about/c3/finances', to: redirect(
      'https://docs.google.com/spreadsheet/ccc?key=0AjmetJxi-p0VdF8tSWwxcHJ1QTJzQWtRSzhMY1ZFSWc',
      status: 302)
    get 'fec'
    get 'help'
    get 'contact'
    get 'press'
    get 'security'
    get 'help/legal', action: 'help_legal'
    get 'tos'
    get 'privacy'
    namespace :press do
      get 'BNA-2015-03-19'
      get 'BNA-2014-05-09'
      get 'BNA-2013-11-15'
    end
    namespace :fec do
      get 'accessibility'
      get 'bitcoin'
      get 'bitcoin/caf', action: 'bitcoin_caf'
      get 'bitcoin/pacs', action: 'bitcoin_pacs'
      get 'bitcoin/aor', to: redirect(
        'https://docs.google.com/document/d/1AVuXrnNPynEcIq07MTgZPCjXMJICxtKeRH0jshYHVk8/',
        status: 302)
      get 'earmarks'
      get 'earmarks/aor', to: redirect(
        'https://docs.google.com/document/d/1YeVdRxEqC8fWnJGl9DgkcNVY6HmkCPEzyRxB_0wttU0/',
        status: 302)
      get 'laundering'
      get 'ravel_weintraub'
      get 'tplf'
      get 'volunteer_ip'
    end
  end

  namespace :facebook do
    resources :payments, only: :create
  end

  namespace :paypal do
    resources :transactions do
      member do
        patch 'refresh'
      end
    end
    resources :notifications, only: :create  # IPN
    resources :transaction_notifications, only: :create # PDT
  end

  namespace :stripe do
    resources :charges
  end
  mount StripeEvent::Engine => '/stripe/callback'

  namespace :admin do
    constraints IsAdmin do
      mount Resque::Server, at: 'resque'
    end
    root to: redirect('/')
    get '*any', to: redirect('/')
  end

  post 'versions/:id/revert' => 'versions#revert', :as => 'revert_version'

  root 'main#index'

  resources :profiles, except: [:show, :update, :edit, :destroy]
  resources :profiles, only: [:show, :update, :edit, :destroy], path: '/'

end

app/models/initiative.rb
class Initiative < ActiveRecord::Base
  resourcify

  ELECTION_TYPES = %w(Primary General Special)
  INITIATOR_TYPES = %w(Legislature Citizen Commission Automatic)
  INITIATIVE_TYPES = ['Constitutional Amendment', 'Statute', 'Bond', 'Veto', 'Question',
                      'Combined Constitutional Amendment & Statute', 'Affirmation', 'Recall']
  validates :election_type, inclusion: { in: ELECTION_TYPES }, allow_blank: true
  validates :initiator_type, inclusion: { in: INITIATOR_TYPES }, allow_blank: true
  validates :initiative_type, inclusion: { in: INITIATIVE_TYPES }, allow_blank: true

  has_paper_trail
  strip_attributes
end

app/controllers/initiatives_controller.rb
class InitiativesController < ApplicationController
  load_and_authorize_resource

  def new
  end

  def create
    @initiative = Initiative.new initiative_params
    if @initiative.save
      redirect_to @initiative
    else
      flash[:error] = 'Error saving initiative'
      render :new
    end
  end

  def show
  end

  def index
  end

  # def search
  # end
  #
  # def destroy
  # end

  def edit
  end

  def update
    if @initiative.update_attributes initiative_params
      redirect_to @initiative
    else
      flash[:error] = 'Error saving initiative'
      render :edit
    end
  end

  private

  def initiative_params
    params.require(:initiative).permit(:jurisdiction, :election_date, :filing_date, :summary_date,
                                       :circulation_deadline, :full_check_deadline, :election_type,
                                       :initiator_type, :initiative_type, :indirect,
                                       :initiative_name, :proposition_name, :title,
                                       :informal_title, :short_summary, :summary, :analysis, :text,
                                       :wikipedia_url, :ballotpedia_url) # but not status
  end
end

app/views/initiatives/_initiative_edit.html.erb
<tr>
  <td><%= f.label :jurisdiction, :class => 'required' %></td>
  <td><%= f.select :jurisdiction, JURISDICTIONS, {:include_blank => true } %></td>
</tr>
<tr>
	<td><%= f.label :election_type %></td>
	<td><%= f.select :election_type, Initiative::ELECTION_TYPES, {:include_blank => true} %>
</tr>
<tr>
  <td><%= f.label :election_date %></td>
  <td><%= f.datepicker :election_date, :size => 10 %></td>
</tr>
<tr>
  <td><%= f.label :filing_date %></td>
  <td><%= f.datepicker :filing_date, :size => 10 %></td>
</tr>
<tr>
  <td><%= f.label :summary_date %></td>
  <td><%= f.datepicker :summary_date, :size => 10 %></td>
</tr>
<tr>
  <td><%= f.label :circulation_deadline %></td>
  <td><%= f.datepicker :circulation_deadline, :size => 10 %></td>
</tr>
<tr>
  <td><%= f.label :full_check_deadline %></td>
  <td><%= f.datepicker :full_check_deadline, :size => 10 %></td>
</tr>
<tr>
	<td><%= f.label :initiator_type, 'Initiator' %></td>
	<td><%= f.select :initiator_type, Initiative::INITIATOR_TYPES, {:include_blank => true} %>
</tr>
	<td><%= f.label :initiative_type %></td>
	<td><%= f.select :initiative_type, Initiative::INITIATIVE_TYPES, {:include_blank => true} %>
<tr>
<tr>
	<td><%= f.label :indirect %></td>
	<td><%= f.check_box :indirect %></td>
</tr>
<tr>
	<td><%= f.label :initiative_name %></td>
	<td><%= f.text_field :initiative_name, :placeholder => "e.g. 11-0035" %></td>
	<td><i>This is the identifier it had while qualifying - should be on secretary of state website</i></td>
</tr>
<tr>
	<td><%= f.label :proposition_name %></td>
	<td><%= f.text_field :proposition_name, :placeholder => "e.g. Proposition 34" %></td>
</tr>
<tr>
	<td><%= f.label :title %></td>
	<td><%= f.text_field :title, :placeholder => "e.g. Death Penalty Repeal" %></td>
	<td><i>don't include redundant info - eg 'Initiative Statue' is a field above</i></td>
</tr>
<tr>
	<td><%= f.label :informal_title %></td>
	<td><%= f.text_field :informal_title, :placeholder => "e.g. The SAFE California Act" %></td>
	<td><i>Go with 1. what it calls itself in the full text, 2. what the proponents call it, 3. what the media call it</i></td>
</tr>
<tr>
	<td><%= f.label :short_summary %></td>
	<td><%= f.text_area :short_summary %></td>
	<td><i>Format using <a href="http://daringfireball.net/projects/markdown/basics">Markdown</a> syntax.</i></td>
</tr>
<tr>
	<td><%= f.label :summary %></td>
	<td><%= f.text_area :summary %></td>
</tr>
<tr>
	<td><%= f.label :analysis %></td>
	<td><%= f.text_area :analysis %></td>
</tr>
<tr>
	<td><%= f.label :text %></td>
	<td><%= f.text_area :text %></td>
</tr>
<tr>
	<td><%= f.label :wikipedia_url %></td>
	<td><%= f.text_field :wikipedia_url %></td>
</tr>
<tr>
	<td><%= f.label :ballotpedia_url %></td>
	<td><%= f.text_field :ballotpedia_url %></td>
</tr>

app/views/initiatives/edit.html.erb
<%= form_for(@initiative, :url => initiative_path(@initiative), :method => :patch, :validate => true) do |f| %>
  <table>
	<%= render :partial => "initiative_edit", :locals => {:f => f} %>
    <tr>
      <td/>
      <td><%= f.submit "Update initiative", data: { disable_with: "Processing…"} %></td>
    </tr>
  </table>
<% end %>

app/views/initiatives/new.html.erb
<%= form_for(@initiative, :url => initiatives_path, :validate => true) do |f| %>
  <table>
	<%= render :partial => "initiative_edit", :locals => {:f => f} %>
    <tr>
      <td/>
      <td><%= f.submit "Add initiative", data: { disable_with: "Processing…"} %></td>
    </tr>
  </table>
<% end %>

app/views/initiatives/show.html.erb
<%= link_to "Edit this initiative", edit_initiative_path(@initiative) %>

<h3><%= @initiative.jurisdiction %> <%= @initiative.proposition_name || @initiative.initiative_name %>: <%= @initiative.title %></h3>
<% if @initiative.informal_title %><h3><%= @initiative.informal_title %></h3><% end %>
<h4><%= @initiative.initiator_type %> initiated <%= "indirect" if @initiative.indirect %> <%= @initiative.initiative_type %> — 
<%= l @initiative.election_date, :format => :long %> <%= @initiative.election_type %> election 
<%= link_to image_tag("wikipedia_16.gif"), @initiative.wikipedia_url if @initiative.wikipedia_url %>
<%= link_to image_tag("ballotpedia_16.png"), @initiative.ballotpedia_url if @initiative.ballotpedia_url %>
</h4>

<%= bettertabs :tabs do |tab| %>
	<%= tab.static :summary do %>
		<%= m @initiative.short_summary %>
	<% end if @initiative.short_summary %>
	<%= tab.static :analysis do %>
		<p><%= m @initiative.summary %></p>
		<p><%= m @initiative.analysis %></p>
	<% end if @initiative.summary or @initiative.analysis %>
	<%= tab.static :full_text do %>
		<%= m @initiative.text %>
	<% end if @initiative.text %>
<% end if  @initiative.short_summary or @initiative.summary or @initiative.analysis or @initiative.text %>