config/routes.rb
Rails.application.routes.draw do
  resources :initiatives
  resources :committees
  resources :identities

  resources :carts do
    resources :cart_items, path: 'items'
  end
  resources :cart_items # in case there isn't a cart

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations:      'users/registrations' }

  devise_scope :user do
    get 'login' => 'devise/sessions#new'
    delete 'logout' => 'devise/sessions#destroy'
    get 'signup' => 'users/registrations#new'
    get 'signup_from_id' => 'users/registrations#new_from_id'
  end

  scope module: 'main' do
    get 'introduction'
    get 'principles'
    get 'strategy'
    get 'faq'
    get 'about/pac/bylaws', to: redirect(
      'https://docs.google.com/document/d/1BbKNamiQdlemLS28iGnkwrwar9vQ9HucK_S1PrZ2mu4/',
      status: 302)
    get 'about/pac/finances', to: redirect(
      'https://docs.google.com/spreadsheet/ccc?key=0AjmetJxi-p0VdGlJSkl5NDkxdlE4bVlLLWtYWEZtcWc',
      status: 302)
    get 'about/pac/fec_reports', to: redirect(
      'http://images.nictusa.com/cgi-bin/fecimg/?C00529743', status: 302)
    get 'about/c4/bylaws', to: redirect(
      'https://docs.google.com/document/d/1uQEetVLONuzNdY_EYvmPX5P5PHC0kgp6kE-cdeVOT0A',
      status: 302)
    get 'about/c4/finances', to: redirect(
      'https://docs.google.com/spreadsheet/ccc?key=0AjmetJxi-p0VdEg3ajFfTDJZM1VPaEZMRmd0LUJ0ZVE',
      status: 302)
    get 'about/c3/bylaws', to: redirect(
      'https://docs.google.com/document/d/1ZU8yNZVC1AnSEKHm9nLN6WlEB6K2Kn2e5J6Mb-e37AI',
      status: 302)
    get 'about/c3/finances', to: redirect(
      'https://docs.google.com/spreadsheet/ccc?key=0AjmetJxi-p0VdF8tSWwxcHJ1QTJzQWtRSzhMY1ZFSWc',
      status: 302)
    get 'fec'
    get 'help'
    get 'contact'
    get 'press'
    get 'security'
    get 'help/legal', action: 'help_legal'
    get 'tos'
    get 'privacy'
    namespace :press do
      get 'BNA-2015-03-19'
      get 'BNA-2014-05-09'
      get 'BNA-2013-11-15'
    end
    namespace :fec do
      get 'accessibility'
      get 'bitcoin'
      get 'bitcoin/caf', action: 'bitcoin_caf'
      get 'bitcoin/pacs', action: 'bitcoin_pacs'
      get 'bitcoin/aor', to: redirect(
        'https://docs.google.com/document/d/1AVuXrnNPynEcIq07MTgZPCjXMJICxtKeRH0jshYHVk8/',
        status: 302)
      get 'earmarks'
      get 'earmarks/aor', to: redirect(
        'https://docs.google.com/document/d/1YeVdRxEqC8fWnJGl9DgkcNVY6HmkCPEzyRxB_0wttU0/',
        status: 302)
      get 'laundering'
      get 'ravel_weintraub'
      get 'tplf'
      get 'volunteer_ip'
    end
  end

  namespace :facebook do
    resources :payments, only: :create
  end

  namespace :paypal do
    resources :transactions do
      member do
        patch 'refresh'
      end
    end
    resources :notifications, only: :create  # IPN
    resources :transaction_notifications, only: :create # PDT
  end

  namespace :stripe do
    resources :charges
  end
  mount StripeEvent::Engine => '/stripe/callback'

  namespace :admin do
    constraints IsAdmin do
      mount Resque::Server, at: 'resque'
    end
    root to: redirect('/')
    get '*any', to: redirect('/')
  end

  post 'versions/:id/revert' => 'versions#revert', :as => 'revert_version'

  root 'main#index'

  resources :profiles, except: [:show, :update, :edit, :destroy]
  resources :profiles, only: [:show, :update, :edit, :destroy], path: '/'

end

app/models/committee.rb
class Committee < ActiveRecord::Base
  self.inheritance_column = :_type_disabled # disable STI
  resourcify

  has_paper_trail
  strip_attributes

  belongs_to :legal_committee, polymorphic: true
  has_many :cart_items
  has_many :carts, through: :cart_items

  validates_associated :legal_committee
  validates :jurisdiction, inclusion: { in: JURISDICTIONS }, presence: true
  validates :full_name, presence: true
  validates :email, :paypal_email, email: true
  validates :url, uri: true

  validate :phone_validate

  # incomplete
  COMMITTEE_TYPES = ['General purpose', 'Small contributor', 'Independent expenditure',
                     'Non-contribution']
  CORPORATION_TYPES = ['501(c)3', '501(c)4', '527 PAC', '527 multicandidate PAC',
                       '527 Super PAC IEOC', '527 Hybrid Super PAC', '527 Non-PAC', '527 SSF',
                       '527 Leadership PAC']

  def phone_validate
    self.phone = Phoner::Phone.parse phone
  rescue Phoner::AreaCodeError
    errors.add :phone, 'must include area code'
  rescue
    errors.add :phone, 'is invalid'
  end
end

app/models/fec/committee.rb
class Fec::Committee < ActiveRecord::Base
  self.table_name = 'fec_committees' # use namespaced table
  self.inheritance_column = :_type_disabled # disable STI
  FILES_DIR = Rails.root.join('db', 'data', 'fec', 'committee_master_files')

  has_paper_trail
  # attr_protected :id, :created_at, :fec_id

  # source: ftp://ftp.fec.gov/FEC/cm12.zip - updated weekly
  #                                                                      length start end
  validates :fec_id, uniqueness: true, length: { is: 9 }, presence: true #  9    0   8
  validates :name, presence: true, length: { maximum: 90 }              # 90    9  98
  validates :treasurer_name, length: { maximum: 38 }                    # 38   99 136
  validates :street_1, :street_2, length: { maximum: 34 }               # 34  137 170 street 1
  #                                                                       34  171 204 street 2
  validates :city, length: { maximum: 18 }                              # 18  205 222
  validates :state, length: { maximum: 2 }                              #  2  223 224
  validates :zip, length: { maximum: 5 }                                #  5  225 229
  validates :designation, allow_nil: true,                              #  1  230 230
                          inclusion: { in: Fec::CommitteeDesignation::TYPES.keys }
  validates :type, inclusion: { in: Fec::CommitteeType::TYPES.keys }    #  1  231 231
  validates :party, length: { maximum: 3 }                              #  3  232 234
  validates :filing_frequency, allow_nil: true,                         #  1  235 235
                               inclusion: { in: Fec::CommitteeFilingFrequency::TYPES.keys }
  validates :interest_group_category,                                   #  1  236 236
    allow_nil: true, inclusion: { in: Fec::CommitteeInterestGroupCategory::TYPES.keys }
  validates :connected_organization_name, length: { maximum: 38 }       # 38  237 274

  # if committee type H S or P
  validates :candidate_id, length: { is: 9 }, allow_nil: true           #  9  275 283

  # not very reliable, since the name is often partial
  belongs_to :connected_organization, foreign_key: 'connected_organization_name',
    primary_key: 'name', class_name: 'Fec::Committee'

  belongs_to :candidate, primary_key: 'fec_id', class_name: 'Fec::Candidate'

  before_validation do
    attribs = attributes.map do |k, v|
      if v.is_a?(String)
        new_v = v.strip.chars.select { |i| i.valid_encoding? }.join # drop invalid UTF-8 chars
        new_v = nil if new_v.blank? || %w(. NONE UNK 0).include?(new_v)
        [k, new_v] if v != new_v
      end
    end
    attribs -= [nil]
    # will only update the changed ones
    self.attributes = attribs.reduce({}) { |h, (k, v)| h[k] = v; h } # an ugly version of to_hash
  end

  def self.new_from_line line, year = nil
    rec = find_or_initialize_by_fec_id line[0..8]
    rec.name                        = line[9..98]
    rec.treasurer_name              = line[99..136]
    rec.street_1                    = line[137..170]
    rec.street_2                    = line[171..204]
    rec.city                        = line[205..222]
    rec.state                       = line[223..224]
    rec.zip                         = line[225..229]
    rec.designation                 = line[230]
    rec.type                        = line[231]
    rec.party                       = line[232..234]
    rec.filing_frequency            = line[235]
    rec.interest_group_category     = line[236]
    rec.connected_organization_name = line[237..274]
    rec.candidate_id                = line[275..283]

    rec.last_update_year ||= year
    rec.last_update_year            = [year, rec.last_update_year].max rescue nil
    rec # not saved - meant for batch import
  end

  def self.update_from_line! line, year = nil
    new_from_line(line, year).save!
  end

  def self.last_updated
    last(order: :updated_at).updated_at rescue nil
  end

  def self.update!
    # New years' "master" files may or may not include previous years' orgs. Bah.
    %w(80 82 84 86 88 90 92 94 96 98 00 02 04 06 08 10 12).each do |year|
      prev_mtime = File.mtime(File.join(FILES_DIR, "cm#{year}.zip")) rescue nil
      # wget -N preserves the ftp server's date
      `cd #{FILES_DIR} && wget -N ftp://ftp.fec.gov/FEC#{year.to_i >= 80 ?
        "/19#{year}" : ''}/cm#{year}.zip`
      mtime = File.mtime(File.join(FILES_DIR, "cm#{year}.zip"))
      next unless !prev_mtime || !last_updated || last_updated < mtime || prev_mtime < mtime

      filename = File.join(FILES_DIR, "fec_commitees_#{year}_#{mtime.to_date}.dta")
      `cd #{FILES_DIR} && unzip -u -j -o #{File.join(FILES_DIR, "cm#{year}.zip")}`
      dataname = case year.to_i
                   when 80..87 then "FOIACM.D#{year}"
                   when 88..97 then 'FOIACM.DTA'
                   else 'foiacm.dta'
                 end
      File.rename File.join(FILES_DIR, dataname), filename

      begin
        file = File.open(filename, 'r')
        # batch = []
        while line = file.gets
          self.update_from_line! line, (year.to_i >= 80 ? 1900 + year.to_i : 2000 + year.to_i)
          # batch << self.new_from_line(line)
          # if batch.size > 1000
          #   self.import batch, :on_duplicate_key_update => (self.column_names -
          #      %w(id fec_id created_at)).map(&:to_sym)
          #   batch = []
          # end
        end
        # self.import batch, :on_duplicate_key_update => (self.column_names -
        #    %w(id fec_id created_at)).map(&:to_sym)
        # batch = []

        true
      ensure
        file.close if defined?(file) && file
      end
    end
  end
end

app/models/fec/committee_type.rb
class Fec::CommitteeType
  TYPES = {
    'C' => 'Communication Cost',
    # Organizations like corporations or unions may prepare communications for their employees or
    #   members that advocate the election of specific candidates and they must disclose them under
    #   certain circumstances. These are usually paid with direct corporate or union funds rather
    #   than from PACs.
    'D' => 'Delegate Committee',
    # Delegate committees are organized for the purpose of influencing the selection of delegates
    #   to Presidential nominating conventions. The term includes a group of delegates, a group of
    #   individuals seeking to become delegates, and a group of individuals supporting delegates.
    'E' => 'Electioneering Communication',
    # Groups (other than PACs) making Electioneering Communications
    'H' => 'House',
    # Campaign committees for candidates for the House of Representatives
    'I' => 'Independent Expenditor (Person or Group)',
    # Individuals or groups (other than PACs) making independent expenditures over $250 in a year
    #   must disclose those expenditures
    'N' => 'PAC - nonqualified',
    # PACs that have not yet been in existence for six months and received contributions from 50
    #   people and made contributions to five federal candidates. These committees have lower
    #   limits for their contributions to candidates.
    'O' => 'Independent Expenditure-Only (Super PAC)',
    # Political Committee that has filed a statement consistent with AO 2010-09 or AO 2010-11. For
    #   more information about independent expenditures
    'P' => 'Presidential',
    # Campaign committee for candidate for President
    'Q' => 'PAC - Qualified',
    # PACs that have been in existence for six months and received contributions from 50 people and
    #   made contributions to five federal candidates
    'S' => 'Senate',
    # Campaign committee for candidate for Senate
    'U' => 'Single Candidate Independent Expenditure',
    # Political Committee For more information about independent expenditures
    'X' => 'Party nonqualified',
    # Party committees that have not yet been in existence for six months and received
    #   contributions from 50 people, unless they are affiliated with another party committee that
    #   has met these requirements.
    'Y' => 'Party Qualified',
    # Party committees that have existed for at least six months and received contributions from 50
    #   people or are affiliated with another party committee that meets these requirements.
    'Z' => 'National Party nonfederal account',
    # National Party nonfederal accounts. Not permitted after enactment of Bipartisan Campaign
    #   Reform Act of 2002.
  }

  def method_missing type
    TYPES[type] || TYPE.rassoc(type)[0]
  end
end

app/controllers/committees_controller.rb
class CommitteesController < ApplicationController
  load_and_authorize_resource class: '::Committee'

  def new
  end

  def create
    @committee = Committee.new committee_params
    if @committee.save
      redirect_to @committee
    else
      flash[:error] = 'Error saving committee'
      render :new
    end
  end

  def show
  end

  def index
  end

  # def search
  # end
  #
  # def destroy
  # end

  def edit
  end

  def update
    if @committee.update_attributes committee_params
      redirect_to @committee
    else
      flash[:error] = 'Error saving committee'
      render :edit
    end
  end

  private

  def committee_params
    params.require(:committee).permit(:jurisdiction, :legal_id, :acronym, :short_name, :full_name,
                                      :type, :foreign_contributions_okay, :corporation_full_name,
                                      :corporation_acronym, :corporation_type, :corporation_ein,
                                      :contact_name, :contact_title, :email, :phone, :url, :party,
                                      :address, :paypal_email, :notes)
  end
end

app/views/committees/_committee_edit.html.erb
<tr>
	<td><%= f.label :jurisdiction, :class => 'required' %></td>
	<td><%= f.select :jurisdiction, JURISDICTIONS, {:include_blank => true } %></td>
</tr>
<tr>
	<td><%= f.label :legal_id, "Legal ID#" %></td>
	<td><%= f.text_field :legal_id %></td>
	<td><i>Committee's state/federal ID #</i></td>
<tr>
	<td><%= f.label :acronym %></td>
	<td><%= f.text_field :acronym %></td>
</tr>
<tr>
	<td><%= f.label :short_name %></td>
	<td><%= f.text_field :short_name, :placeholder => "e.g. No on 29" %></td>
</tr>
<tr>
	<td><%= f.label :full_name %></td>
	<td><%= f.text_field :full_name, :length => 200, :placeholder => "e.g. No on 29—Californians Against Out-of-Control Taxes and Spending, a coalition of taxpayers, small businesses, law enforcement and labor" %></td>
</tr>
<tr>
	<td><%= f.label :type %></td>
	<td><%= f.text_field :type %></td>
	<td><i>general purpose, small contributor, independent expenditure, non-contribution, etc</i></td>
</tr>
<tr>
	<td><%= f.label :foreign_contributions_okay %></td>
	<td><%= f.check_box :foreign_contributions_okay %></td>
	<td><i>leave false until we get FEC advice</i></td>
<tr><td colspan=2><hr></td></tr>
<tr>
	<td><%= f.label :corporation_full_name %></td>
	<td><%= f.text_field :corporation_full_name %></td>
	<td><i>The corporation that owns this committee</i></td>
</tr>
<tr>
	<td><%= f.label :corporation_acronym %></td>
	<td><%= f.text_field :corporation_acronym %></td>
</tr>
<tr>
	<td><%= f.label :corporation_type %></td>
	<td><%= f.text_field :corporation_type %></td>
	<td><i>501(c)3, 501(c)4, 527 PAC, 527 multicandidate PAC, 527 Super PAC, 527 Hybrid Super PAC, 527 Non-PAC, 527 SSF, 527 Leadership PAC, etc</i></td>
</tr>
<tr>
	<td><%= f.label :corporation_ein %></td>
	<td><%= f.text_field :corporation_ein %></td>
</tr>
<tr><td colspan=2><hr></td></tr>
<tr>
	<td><%= f.label :contact_name %></td>
	<td><%= f.text_field :contact_name %></td>
</tr>
<tr>
	<td><%= f.label :contact_title %></td>
	<td><%= f.text_field :contact_title %></td>
</tr>
<tr>
	<td><%= f.label :email %></td>
	<td><%= f.email_field :email %></td>
</tr>
<tr>
	<td><%= f.label :phone %></td>
	<td><%= f.text_field :phone %></td>
</tr>
<tr>
	<td><%= f.label :url %></td>
	<td><%= f.text_field :url %></td>
</tr>
<tr>
	<td><%= f.label :party %></td>
	<td><%= f.text_field :party %></td>
	<td><i>if affiliated, de facto or official</i></td>
</tr>
<tr><td colspan=2><hr></td></tr>
<tr>
	<td><%= f.label :address %></td>
	<td><%= f.text_field :address %></td>
	<td><i>for sending checks</i></td>
</tr>
<tr>
	<td><%= f.label :paypal_email %></td>
	<td><%= f.text_field :paypal_email %></td>
</tr>
<tr><td colspan=2><hr></td></tr>
<tr>
	<td><%= f.label :notes %></td>
	<td><%= f.text_area :notes %></td>
	<td><i>MYL internal</i></td>
</tr>

app/views/committees/edit.html.erb
<%= form_for(@committee, :url => committee_path(@committee), :method => :patch, :validate => true) do |f| %>
  <table>
	<%= render :partial => "committee_edit", :locals => {:f => f} %>
    <tr>
      <td/>
      <td><%= f.submit "Update committee", data: { disable_with: "Processing…"} %></td>
    </tr>
  </table>
<% end %>

app/views/committees/index.html.erb
<%= link_to "Add new", new_committee_path %>

<table>
	<tr>
		<th>Jurisdiction</th>
		<th>Name</th>
	</tr>
	<% @committees.each do |committee| %>
	<tr>
		<td><%= committee.jurisdiction %></td>
		<td><%= link_to committee.short_name, committee %></td>
	</tr>
	<% end %>
</table>

app/views/committees/new.html.erb
<%= form_for(@committee, :url => committees_path, :validate => true) do |f| %>
  <table>
	<%= render :partial => "committee_edit", :locals => {:f => f} %>
    <tr>
      <td/>
      <td><%= f.submit "Add committee", data: { disable_with: 'Processing…' } %></td>
    </tr>
  </table>
<% end %>

app/views/committees/show.html.erb
<%= render partial: '/cart_items/new', committee: @committee %>

<%= link_to "Edit this committee", edit_committee_path(@committee) %>

<h3><%= @committee.short_name || @committee.full_name %> <%= "(#{@committee.acronym})" if @committee.acronym %> <%= link_to "website", @committee.url if @committee.url %></h3>
<% if @committee.short_name and @committee.full_name %><h4><%= @committee.full_name %></h4><% end %>
<h4>
	<%= @committee.jurisdiction %> <%= @committee.type %> committee, ID#<%= @committee.legal_id %> <%= "(#{@committee.party})" if @committee.party %>
</h4>

<i>This committee <b><%= @committee.foreign_contributions_okay ? "can" : "cannot" %></b> accept foreign national contributions.</i>

<% if @committee.corporation_full_name %>
	<p>Run by <%= @committee.corporation_ful_name %> <%= "(#{@committee.corporation_acronym})" if @committee.corporation_acronym %> 	
	<%= @committee.corporation_type %> <%= "EIN #{@committee.corporation_ein }" if @committee.corporation_ein %></p>
<% end %>

<p>
	<%= @committee.contact_name %> <%= "(#{@committee.contact_title})" if @committee.contact_title %>
	<%= link_to @committee.email if @committee.email %>
	<%= @committee.address %>
</p>

<% if user_signed_in? and current_user.id == 1 %>
	<p>Status: <%= @committee.status %></p>
	<p>Notes: <%= @commitee.notes %></p>
<% end %>

<%= link_to @committee.legal_commmittee if @committee.legal_committee %>